[2018-12-09 13:58:09] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 58, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 108, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 60, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 116, in OnGetRank
    pubglobalmanager.CallManagerFunc("demo", "GetRank", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 90, in GetRank
    rankList[i] = [row[0], row[1], row[2]]
IndexError: list assignment index out of range
---------extra---------
recvfail2
[2018-12-09 13:58:56] ---------TraceErr---------
Traceback (most recent call last):
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 58, in Recv
    self.OnCommand(dPackData)
  File "C:\Users\licong\Desktop\server\server\code\clientsocket\clientobject.py", line 108, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "C:\Users\licong\Desktop\server\server\code\commandctrl\manager.py", line 60, in OnCommand
    oFunc(oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 117, in OnGetRank
    pubglobalmanager.CallManagerFunc("demo", "GetRank", oClient, dData)
  File "C:\Users\licong\Desktop\server\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "C:\Users\licong\Desktop\server\server\code\demo.py", line 90, in GetRank
    rankList[i] = [row[0], row[1], row[2]]
IndexError: list assignment index out of range
---------extra---------
recvfail2
[2019-03-19 14:10:17] ---------TraceErr---------
Traceback (most recent call last):
  File "E:\work\VoidWarrior\server\code\clientsocket\clientobject.py", line 36, in run
    self.Recv(sData)
  File "E:\work\VoidWarrior\server\code\clientsocket\clientobject.py", line 54, in Recv
    self.OnCommand(dPackData)
  File "E:\work\VoidWarrior\server\code\clientsocket\clientobject.py", line 104, in OnCommand
    commandctrl.OnCommand(self, dData)
  File "E:\work\VoidWarrior\server\code\commandctrl\__init__.py", line 15, in OnCommand
    oManager.OnCommand(oClient, dData)
  File "E:\work\VoidWarrior\server\code\mutexlock\__init__.py", line 18, in ___AutoLock
    ret = func(*args, **kwargs)
  File "E:\work\VoidWarrior\server\code\commandctrl\manager.py", line 54, in OnCommand
    oFunc(oClient, dData)
  File "E:\work\VoidWarrior\server\code\demo.py", line 134, in OnLogin
    pubglobalmanager.CallManagerFunc("demo", "Login", oClient, dData)
  File "E:\work\VoidWarrior\server\code\pubglobalmanager.py", line 30, in CallManagerFunc
    return oFunc(*args)
  File "E:\work\VoidWarrior\server\code\demo.py", line 101, in Login
    oClient.Send(dReturn)
UnboundLocalError: local variable 'dReturn' referenced before assignment
---------extra---------
recvfail2
